const PDFDocument = require("pdfkit");
const db = require("../config/db");

exports.generateSEOReportPDF = (req, res) => {
  const { reportId } = req.params;

  const query = "SELECT * FROM seo_reports WHERE id = ?";

  db.query(query, [reportId], (err, results) => {
    if (err) {
      return res.status(500).json({ message: err.message });
    }

    if (results.length === 0) {
      return res.status(404).json({ message: "Report not found" });
    }

    const report = results[0];

    const doc = new PDFDocument();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=seo-report-${reportId}.pdf`
    );

    doc.pipe(res);

    doc.fontSize(24).text("RankBoost AI - SEO Report", {
      align: "center",
    });

    doc.moveDown();

    doc.fontSize(14).text(`Website: ${report.url}`);
    doc.text(`SEO Score: ${report.seo_score}/100`);
    doc.text(`Title: ${report.title}`);
    doc.text(`Title Length: ${report.title_length}`);
    doc.text(`Meta Description: ${report.meta_description}`);
    doc.text(`Meta Description Length: ${report.meta_description_length}`);
    doc.text(`Total Images: ${report.total_images}`);
    doc.text(`Images Without Alt: ${report.images_without_alt}`);
    doc.text(`Total Links: ${report.total_links}`);
    doc.text(`Word Count: ${report.word_count}`);

    doc.moveDown();

    doc.fontSize(18).text("SEO Suggestions");
    doc.moveDown();

    let suggestions = [];

    try {
      suggestions = JSON.parse(report.suggestions);
    } catch {
      suggestions = [];
    }

    suggestions.forEach((item, index) => {
      doc.fontSize(12).text(`${index + 1}. ${item}`);
    });

    doc.moveDown();

    doc.fontSize(10).text("Generated by RankBoost AI", {
      align: "center",
    });

    doc.end();
  });
};